FROM resin/%%RESIN_MACHINE_NAME%%-python:3.5
RUN apt-get update && apt-get install -yq openvpn && \
           apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY entry.sh .

CMD ["bash", "entry.sh"]
